version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi

  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
        - MYSQL_DATABASE=bankvizi_ainews
        - MYSQL_USER=bankvizi_ainews
        - MYSQL_PASSWORD=j5c5DG7#e#

volumes:
  my-db:
