import os

from sqlalchemy import create_engine

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_ORGANIZATION = os.getenv('OPENAI_ORGANIZATION')

DB_TOPICS_DIALECT = os.getenv('DB_TOPICS_DIALECT')
DB_TOPICS_DRIVER = os.getenv('DB_TOPICS_DRIVER')
DB_TOPICS_USERNAME = os.getenv('DB_TOPICS_USERNAME')
DB_TOPICS_PASSWORD = os.getenv('DB_TOPICS_PASSWORD')
DB_TOPICS_HOST = os.getenv('DB_TOPICS_HOST')
DB_TOPICS_PORT = os.getenv('DB_TOPICS_PORT')
DB_TOPICS_DATABASE = os.getenv('DB_TOPICS_DATABASE')

DB_TOPICS_ENGINE = create_engine(
    f'{DB_TOPICS_DIALECT}+{DB_TOPICS_DRIVER}://{DB_TOPICS_USERNAME}:{DB_TOPICS_PASSWORD}@{DB_TOPICS_HOST}:{DB_TOPICS_PORT}/{DB_TOPICS_DATABASE}'
).connect()
